### ISSUE TITLE
Fuzzy completion like in slime for Common Lisp

### ISSUE THREAD

**Issue by bulat-nazarov-medved** [alexander-yakushev/compliment#17]
Need fully fuzzy completion  like in slime for Common Lisp. Current fuzzyness is too simple.

**Comment by laurentpetit** [comment]
CCW uses fuzzy completion, and "solves" (empirically) the possible confusion issue by sorting the the list by first making "full match" come first, then fuzzy matches with preference for narrower matches over broader matches. So far it's worked well. Also, if the unfiltered list is too big (empirical limit of 50 elements), fuzzy completion filtering is not used, plain ".contains" filtering is used.

Even though it seems quite non scientific and somewhat subjective, this combo has worked well in practice, to the extent that nobody complained that true "match-considering-separators" has not been implemented!

**Comment by alexander-yakushev** [comment]
This might work, but will require a significant rewriting of most sources. Performance also needs to be considered. Overall, I don't feel like it is worth the trouble, few examples provided in this thread are too marginal to bother. As I've said before, completion has two goals — exploratory, when you don't know what you want; and auxiliary, when you do. It doesn't have a goal to play Scrabble with user and guess what they meant by whatever symbols they typed in.

Add the fact, that fuzzy matching has to be implemented on both Compliment side (Clojure) and Emacs auto-complete side (Elisp), because AC does not repoll the backend as user continuous typing after initial completion request. Also, matching first symbol can no longer be used as a hard filter for candidates because of #20.

If I get a working and sane pull request that covers all the above considerations, I will accept it, but I highly doubt it is something that one should put time into.

**Comment by laurentpetit** [comment]
You are probably right and I should refrain myself from working on it yet. I will first deliver CCW with what compliment offers through cider, and wait for the users reactions. And then wait a little bit more (once they're used to the new behavior). Only then will I consider true fuzzy completion again, if the complaints stream does not stop.

I'm not sure what you mean by "matching first symbol can no longer be used ..."?

**Comment by alexander-yakushev** [comment]
There was an argument in this thread that regardless of the fuzziness completion should only work if the first symbol of the prefix matches the first symbol of the candidate. And it was so, until #20 introduced candidates that don't confirm to this rule (`Arr` expands to `java.util.ArrayList`). While this change touches only the classname source, Emacs side of the completion doesn't know about sources, and it uses one-size-fits-all fuzzy filter. Which means I no longer use first-symbol rule when matching.
