### ISSUE TITLE
Class candidates are always tagged with an :ns of *ns*

### ISSUE THREAD

**Issue by cichli** [alexander-yakushev/compliment#21]
e.g.

```clojure
user> (compliment.core/completions "Thre" {:tag-candidates true})
```

returns

```clojure
({:ns "user", :type :class, :candidate "Thread"}
 {:ns "user", :type :class, :candidate "ThreadDeath"}
 {:ns "user", :type :class, :candidate "ThreadGroup"}
 {:ns "user", :type :class, :candidate "ThreadLocal"}
 {:ns "user", :type :class, :candidate "Thread$State"}
 {:ns "user", :type :class, :candidate "Thread$UncaughtExceptionHandler"})
```

**Comment by alexander-yakushev** [comment]
This is correct. These are shortcut names for classes that were imported into the current namespace. If it makes any sense at all to add ns tag to them, then the current namespace should be used for that.

**Comment by cichli** [comment]
Sorry, should have been clear: I think the bug is that :ns exists at all here.

Do you think it would make sense to include the package containing the class (presumably under a different key)?

**Comment by alexander-yakushev** [comment]
:ns is there because all candidates in ns_mapping source has that. After all, it is up to frontend dev to use it or not.

Tagging such candidates with their package name might make sense, but I can't see how it can be used right now in frontend. Popup help in ac-cider already shows full package name for those classes, and littering each candidate with it's package will bring confusion. Besides, you cannot import two classes with same names into a single namespace, so you usually know anyway which package that class belongs to (because you imported it).

**Comment by cichli** [comment]
That makes sense - it's simple to filter these out on the client anyway. I was thinking that since CIDER annotates non-namespace-qualified clojure candidates with their namespace, it would make sense to annotate Java classes with the package they belong to.

**Comment by cichli** [comment]
Sometimes you do have so many classes imported that it's hard to remember which packages they all belong to though, or you might be working with a codebase you're unfamiliar with - the extra context of the package name could be helpful here. I think annotating just unqualified classes with their package wouldn't introduce too much clutter, but as you say - looking up the documentation instead is zero effort, so it doesn't make a huge difference :-).

**Comment by alexander-yakushev** [comment]
Well, I don't see how it can harm.
