### ISSUE TITLE
is there an example how to use `compliment` within emacs but without cider?

### ISSUE THREAD

**Issue by zcaudate** [alexander-yakushev/compliment#78]
I'd like to move off of cider but my elisp is only good enough to do some basic configuration changes.

I've asked here https://github.com/sanel/monroe/issues/38 but thought I'd ask here as well.

Is there a configuration for compliment strictly for company-mode without going through cider?

**Comment by alexander-yakushev** [comment]
Hello Chris. There is currently no "official" way to use Compliment in Emacs without CIDER. Depending on what you use instead of CIDER (inf-clojure or something else), it should be possible to marry company-mode, Emacs-Clojure interaction layers, and Compliment. But I would not be able to help you much with it, unfortunately.

Maybe this helps a little bit, here's the self-contained Elisp module for Compliment, it still uses CIDER but just the eval functionality, so you might be able to replace it with your emacs-clojure layer. https://github.com/purcell/ac-cider-compliment/blob/master/ac-cider-compliment.el

**Comment by zcaudate** [comment]
@alexander-yakushev:

Looking more closely into `inf-clojure`, that  might be the way to go for me but it has it's own quirks. I tried just now - both eldoc and compliment are working but errors print in the repl and so does both eldoc and code completion.

<img width="614" alt="Screen Shot 2021-07-20 at 12 47 48 am" src="https://user-images.githubusercontent.com/1455572/126196871-04529ad0-ef32-40e5-ac32-4888c62aabb1.png">

----

Currently with cider, on connection from emacs, the editor stalls for about a minute and  there's a ridiculous amount of cpu usage before emacs become responsive again. This is after `lein repl` had also taken about 1 minute to load before that.

I thought it may be related to the autocomplete system (as I have quite a lot of vars) but there doesn't seem to be this problem with `inf-clojure` and the compliment setup I tried just now.

---

I'll close this as I think I have most of the parts of what I need to get a decent setup going. Thanks for your help.
